### ISSUE TITLE
Security Issue(postgreSql

### ISSUE THREAD

**Issue by ousamabenyounes** [vvinutna/watersrc#1]
index.js file has been compromised and your login/pwd are now visible on this this project

The jdbc string is available: const connectionString = 'postgres://zsullibbcjradi:31f72543073d43fb185647654c64ce799395244eb1adc99dec75598472a603a8@ec2-174-129-37-15.compute-1.amazonaws.com:5432/d3thlija746umv?ssl=true';

to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

Hope this will help you :)

**Comment by vvinutna** [comment]
I do not see that my login and pwd are visible in the index.js file.  Is it a security issue that the link to my database is visible. If so, is there a way to connect to my database without making the link visible?

**Comment by ousamabenyounes** [comment]
your login: zsullibbcjradi
your password: 31f72543073d43fb185647654c64ce799395244eb1adc99dec75598472a603a8

taken from your complete jdbc string 
postgres://zsullibbcjradi:31f72543073d43fb185647654c64ce799395244eb1adc99dec75598472a603a8@ec2-174-129-37-15.compute-1.amazonaws.com:5432/d3thlija746umv?ssl=true';

Is it a security issue that the link to my database is visible
YES of course...if you confirm that these are your login pwd, then you must remove them from this repository because anyone can connect on it...
change your login / pwd on amazon EC2

And you can remove the project.
Remove the link from your project, and push the project with a variable instead

in the open source project you'll have:

jdbcString = '' // here you put the real jdbc string

the comment explains what other users have to do if they need to connect with your source code...they ll have to put their own EC2 / Amazon jdbc string 

Hope i was clear

Good luck

**Comment by vvinutna** [comment]
Okay, thank you for your help!
